### ISSUE TITLE
Namespace inconsistencies

### ISSUE THREAD

**Issue by kimipsen** [dotnetdev-kr/Experimental.System.Messaging#1]
Consider using only a single namespace for all classes. As it currently is, the `Trustee` class is located in the System.Messaging namespace, while MessageQueue exists in Experimental.System.Messaging.
This can result in conflicts when using both the experimental nuget and the original library in the same project.

**Comment by rkttu** [comment]
I posted a new version of the package as I solved your issue. There will be a package available that fixes the problem in version 1.1.0. Thank you for registering your issue. 👍

**Comment by rkttu** [comment]
You can now install the new package with this command - `dotnet add package Experimental.System.Messaging --version 1.1.0`

https://www.nuget.org/packages/Experimental.System.Messaging
